using FirebirdSql.Data.FirebirdClient;
using ImapCertWatcher.Models;
using ImapCertWatcher.Utils;
using System;
using System.Collections.Generic;
using System.Data;

namespace ImapCertWatcher.Data
{
    public class DbHelper
    {
        private readonly string _connectionString;

        public DbHelper(AppSettings s)
        {
            var csb = new FbConnectionStringBuilder
            {
                Database = s.FirebirdDbPath,
                UserID = s.FbUser,
                Password = s.FbPassword,
                Dialect = s.FbDialect,
                ServerType = FbServerType.Default // local file
            };
            _connectionString = csb.ToString();
            EnsureDatabaseAndTable();
        }

        private void EnsureDatabaseAndTable()
        {
            // Firebird: если файла нет — его нужно создать.
            var csb = new FbConnectionStringBuilder(_connectionString);
            if (!System.IO.File.Exists(csb.Database))
            {
                // создаём БД
                FbConnection.CreateDatabase(_connectionString);
            }

            using (var con = new FbConnection(_connectionString))
            {
                con.Open();
                var cmd = con.CreateCommand();
                cmd.CommandText = @"
                    CREATE TABLE IF NOT EXISTS CERTS (
                      ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      MAIL_UID VARCHAR(100) UNIQUE,
                      FIO VARCHAR(200),
                      DATE_START TIMESTAMP,
                      DATE_END TIMESTAMP,
                      DAYS_LEFT INTEGER,
                      SUBJECT VARCHAR(250),
                      RECEIVED TIMESTAMP
                    );";
                // NOTE: Firebird 2.5 не поддерживает "CREATE TABLE IF NOT EXISTS", так что на старых серверах можно
                // поймать ошибку и игнорировать её. Здесь сделана попытка — в крайнем случае выполнить проверку.
                try
                {
                    cmd.ExecuteNonQuery();
                }
                catch (FbException)
                {
                    // fallback: проверим вручную, есть ли таблица
                    cmd.CommandText = "SELECT COUNT(*) FROM rdb$relations WHERE rdb$relation_name = 'CERTS'";
                    var exists = Convert.ToInt32(cmd.ExecuteScalar()) > 0;
                    if (!exists)
                    {
                        cmd.CommandText = @"
                        CREATE TABLE CERTS (
                          ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          MAIL_UID VARCHAR(100) UNIQUE,
                          FIO VARCHAR(200),
                          DATE_START TIMESTAMP,
                          DATE_END TIMESTAMP,
                          DAYS_LEFT INTEGER,
                          SUBJECT VARCHAR(250),
                          RECEIVED TIMESTAMP
                        );";
                        cmd.ExecuteNonQuery();
                    }
                }
            }
        }

        public void InsertOrUpdate(CertEntry e)
        {
            using (var con = new FbConnection(_connectionString))
            {
                con.Open();
                // пытаемся вставить, если уже есть — обновляем
                var cmd = con.CreateCommand();
                cmd.CommandText = @"
                    UPDATE CERTS SET
                      FIO = @fio,
                      DATE_START = @ds,
                      DATE_END = @de,
                      DAYS_LEFT = @dl,
                      SUBJECT = @sub,
                      RECEIVED = @rec
                    WHERE MAIL_UID = @uid;
                    IF (ROW_COUNT = 0) THEN
                    INSERT INTO CERTS (MAIL_UID, FIO, DATE_START, DATE_END, DAYS_LEFT, SUBJECT, RECEIVED)
                      VALUES (@uid, @fio, @ds, @de, @dl, @sub, @rec);";
                cmd.Parameters.AddWithValue("uid", e.MailUid);
                cmd.Parameters.AddWithValue("fio", e.Fio);
                cmd.Parameters.AddWithValue("ds", e.DateStart);
                cmd.Parameters.AddWithValue("de", e.DateEnd);
                cmd.Parameters.AddWithValue("dl", e.DaysLeft);
                cmd.Parameters.AddWithValue("sub", e.Subject);
                cmd.Parameters.AddWithValue("rec", e.Received);
                try
                {
                    cmd.ExecuteNonQuery();
                }
                catch (FbException)
                {
                    // старые версии драйвера / SQL: сделаем более надёжно — проверим наличие строки
                    cmd.CommandText = "SELECT ID FROM CERTS WHERE MAIL_UID = @uid";
                    var idObj = cmd.ExecuteScalar();
                    if (idObj != null && idObj != DBNull.Value)
                    {
                        cmd.CommandText = @"
                          UPDATE CERTS SET
                            FIO = @fio,
                            DATE_START = @ds,
                            DATE_END = @de,
                            DAYS_LEFT = @dl,
                            SUBJECT = @sub,
                            RECEIVED = @rec
                          WHERE MAIL_UID = @uid";
                        cmd.ExecuteNonQuery();
                    }
                    else
                    {
                        cmd.CommandText = @"
                          INSERT INTO CERTS (MAIL_UID, FIO, DATE_START, DATE_END, DAYS_LEFT, SUBJECT, RECEIVED)
                            VALUES (@uid, @fio, @ds, @de, @dl, @sub, @rec)";
                        cmd.ExecuteNonQuery();
                    }
                }
            }
        }

        public List<CertEntry> LoadAll()
        {
            var list = new List<CertEntry>();
            using (var con = new FbConnection(_connectionString))
            {
                con.Open();
                var cmd = con.CreateCommand();
                cmd.CommandText = "SELECT ID, MAIL_UID, FIO, DATE_START, DATE_END, DAYS_LEFT, SUBJECT, RECEIVED FROM CERTS ORDER BY DATE_END";
                using (var r = cmd.ExecuteReader())
                {
                    while (r.Read())
                    {
                        var e = new CertEntry
                        {
                            Id = r.GetInt32(0),
                            MailUid = r.IsDBNull(1) ? null : r.GetString(1),
                            Fio = r.IsDBNull(2) ? null : r.GetString(2),
                            DateStart = r.IsDBNull(3) ? DateTime.MinValue : r.GetDateTime(3),
                            DateEnd = r.IsDBNull(4) ? DateTime.MinValue : r.GetDateTime(4),
                            DaysLeft = r.IsDBNull(5) ? 0 : r.GetInt32(5),
                            Subject = r.IsDBNull(6) ? null : r.GetString(6),
                            Received = r.IsDBNull(7) ? DateTime.MinValue : r.GetDateTime(7)
                        };
                        list.Add(e);
                    }
                }
            }
            return list;
        }
    }
}
